name = "nada-auth-v2"
main = "src/app/index.ts"
compatibility_date = "2024-12-06"
minify = true
compatibility_flags = ["nodejs_compat"]
[assets]
directory = "dist"
binding = "ASSETS"
run_worker_first = true

[define]
"import.meta.env.DEV" = "false"
"import.meta.env.PROD" = "true"

[[kv_namespaces]]
binding = "GuildConfigs"
id = "c89441ee2d454da3bba25c9ef3b5a849"

[[kv_namespaces]]
binding = "AuthNRequests"
id = "3d055498d36c4cce8f87feb19ee1a0f1"

[[kv_namespaces]]
binding = "Sessions"
id = "8d9392625ca04727a87a5ddf09a2b459"

[env.dev.define]
"import.meta.env.DEV" = "true"
"import.meta.env.PROD" = "false"

[[env.dev.kv_namespaces]]
binding = "GuildConfigs"
id = "c89441ee2d454da3bba25c9ef3b5a849"

[[env.dev.kv_namespaces]]
binding = "AuthNRequests"
id = "3d055498d36c4cce8f87feb19ee1a0f1"

[[env.dev.kv_namespaces]]
binding = "Sessions"
id = "8d9392625ca04727a87a5ddf09a2b459"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability.logs]
enabled = true
