name: Compile and Lint
on:
    pull_request:
permissions:
    contents: read
jobs:
    compile_and_lint:
        runs-on: ubuntu-latest
        name: Compile and Lint
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - uses: actions/setup-node@v4
              with:
                  node-version: "22.14.0"
            - run: bun i --frozen-lockfile
            - run: bun tsc
            - run: bun lint
            - name: Check outdated patches
              run: bun check-outdated-patches
